backend:
  image:
    repository: tu-backend-image
    tag: latest
  replicas: 2
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
  db:
    host: pedido-app-postgresql
    port: 5432
    name: pedidos
    user: admin
    password: supersecret

postgresql:
  auth:
    username: admin
    password: supersecret
    database: pedidos
  primary:
    persistence:
      enabled: true
      size: 1Gi
